name = "PropertyFunctions"
uuid = "09e99361-2bb8-48a2-a80f-de58f0739eb4"
version = "0.3.0"

[deps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
FunctionChains = "8e6b2b91-af83-483e-ba35-d00930e4cf9b"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[extensions]
PropertyFunctionsAccessorsExt = "Accessors"
PropertyFunctionsFunctionChainsExt = "FunctionChains"
PropertyFunctionsReactantExt = "Reactant"

[compat]
Accessors = "0.1"
FunctionChains = "0.2.6"
Reactant = "0.2"
StructArrays = "0.7"
Tables = "1"
julia = "1.10"
